### PR TITLE
修复响应头notice

### PR DESCRIPTION
**Pull request by jtunggit**
修复响应头 当行没有 : 时错出 bug,如:HTTP/1.1 200 OK 会抛 notice 错误

### CODE REVIEW

**Comment by Yurunsoft** [comment]
我这边不会出现notice，能否提供一下会出现notice的调试代码？

**Comment by jtunggit** [comment]
例如去百度搜索关键词,然后打开,例如这个 url:
http://m.baidu.com/from=0/bd_page_type=1/ssid=0/uid=0/pu=sz%40224_220%2Cta%40iphone___3_537%2Cusm%402/baiduid=05629C3F084A2D2391252FD960DAAD7D/w=10_10_/t=iphone/l=1/tc?ref=www_iphone&lid=11739264560246015059&order=7&fm=alop&waplogo=1&tj=www_normal_7_10_10_title&vit=osres&waput=2&cltj=normal_title&asres=1&nt=wnor&title=PHP%E6%97%A2%E7%84%B6%E8%BF%99%E4%B9%88%E7%83%82%2C%E9%82%A3%E5%AE%83%E6%98%AF%E6%80%8E%E4%B9%88%E7%81%AB%E8%B5%B7%E6%9D%A5%E7%9A%84%3F-%E7%9F%A5%E4%B9%8E&dict=-1&w_qd=IlPT2AEptyoA_yipJF3&sec=21657&di=71d33e1351015d16&bdenc=1&nsrc=IlPT2AEptyoA_yixCFOxXnANedT62v3IGti0LSVQB8SxokDyqRLuFNFtVjb5LjrIBZOlcTfMtBsE

**Comment by Yurunsoft** [comment]
试了一下，也没有出notice
image
image

**Comment by jtunggit** [comment]
你的 error_reportting 忽略了?

**Comment by Yurunsoft** [comment]
没有忽略，其它notice能显示的。。你是什么版本？

**Comment by jtunggit** [comment]
php -version
PHP 7.1.5-1+deb.sury.org~xenial+1 (cli) (built: May 11 2017 14:07:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by Yurunsoft** [comment]
PHP 7.0.1 (cli) (built: Dec 16 2015 13:36:28) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

PHP5.3和5.5也都试过了，没有出现notice

**Comment by Yurunsoft** [comment]
image
下了个7.1试了下，也没有notice

**Comment by jtunggit** [comment]
$http->retry(3)
            ->ua('Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1')
            ->referer('https://m.baidu.com/')
            ->accept('text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8')
            ->acceptLanguage('zh-CN,zh;q=0.8');
我的代码如上,百度的头里面会返回最后一行是 HTTP 1.0 OK,没有 : 分隔,所以就会notice

**Comment by jtunggit** [comment]
array(26) {
  [0]=>
  string(30) "HTTP/1.1 301 Moved Permanently"
  [1]=>
  string(35) "Date: Sun, 11 Jun 2017 12:18:29 GMT"
  [2]=>
  string(23) "Content-Type: text/html"
  [3]=>
  string(19) "Content-Length: 178"
  [4]=>
  string(22) "Connection: keep-alive"
  [5]=>
  string(74) "Set-Cookie: aliyungf_tc=AQAAAKM4xUYKGAoAqRn5OjEUMpg8l6TB; Path=/; HttpOnly"
  [6]=>
  string(49) "Location: https://www.zhihu.com/question/28596521"
  [7]=>
  string(24) "X-Req-ID: 28DEA9593D3515"
  [8]=>
  string(11) "Server: ZWS"
  [9]=>
  string(21) "Vary: Accept-Encoding"
  [10]=>
  string(0) ""
  [11]=>
  string(15) "HTTP/1.1 200 OK"
  [12]=>
  string(35) "Date: Sun, 11 Jun 2017 12:18:36 GMT"
  [13]=>
  string(38) "Content-Type: text/html; charset=utf-8"
  [14]=>
  string(21) "Content-Length: 38284"
  [15]=>
  string(22) "Connection: keep-alive"
  [16]=>
  string(74) "Set-Cookie: aliyungf_tc=AQAAAMcYP2natQUAqRn5OlAuy4YtXcGd; Path=/; HttpOnly"
  [17]=>
  string(16) "Pragma: no-cache"
  [18]=>
  string(38) "Expires: Fri, 02 Jan 2000 00:00:00 GMT"
  [19]=>
  string(21) "X-Frame-Options: DENY"
  [20]=>
  string(91) "Cache-Control: private,no-store,max-age=0,no-cache,must-revalidate,post-check=0,pre-check=0"
  [21]=>
  string(420) "Content-Security-Policy: default-src * blob:;img-src * data: blob:;frame-src 'self' *.zhihu.com getpocket.com note.youdao.com safari-extension://com.evernote.safari.clipper-Q79WDW8YH9 weixin: static.hdslb.com player.youku.com v.qq.com;script-src 'self' *.zhihu.com *.google-analytics.com zhstatic.zhihu.com res.wx.qq.com 'unsafe-eval' unpkg.zhimg.com blob:;style-src 'self' *.zhihu.com 'unsafe-inline';connect-src * wss:"
  [22]=>
  string(25) "X-Req-ID: 200FC73593D351C"
  [23]=>
  string(64) "X-Req-SSL: proto=TLSv1.2,sni=,cipher=ECDHE-RSA-AES256-GCM-SHA384"
  [24]=>
  string(11) "Server: ZWS"
  [25]=>
  string(21) "Vary: Accept-Encoding"
}
PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 1'

yurun-http/HttpResponse.php:110

**Comment by Yurunsoft** [comment]
用上面的代码确实有问题，下次更新合并过来

**Pull request merged**
